Bump plugin to Java 11
jenkinsci/thin-backup-plugin pull request #39
Opened 2022-10-01 13:02 UTC by mkemmerz

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Doings

- Bump the plugin to java 11
- Use Java 11 nodes to build the plugin in CI/CD
- Bump dependencies to mirror newest versions (e.g. jenkinci-plugins, junit and some other util dependencies)
- Bump property version for jenkins.version to 2.372
- Set working directory of surefire plugin to ${java.io.tmpdir}
- Introduce @Rule for testcases, those are failing otherwise with java 11

2022-10-04 19:01 UTC, mkemmerz commented
Almost done. Weirdly enough I have to create a tmp folder manually in the /target for the tests to run correctly. The Rule for the temporary folder seems to have issues here? Maybe related to my Windows system?

2022-10-09 15:06 UTC, StefanSpieker commented
That looks quite promissing. I think we can improve it a little bit, please take a look at #34 - you can remove a cuple of versions and pick up the numbers from the parent.

2022-10-13 08:32 UTC, mkemmerz commented
I merged https://github.com/jenkinsci/thin-backup-plugin/pull/34 into this branch so it is based on your pom updates now.

2022-10-17 09:00 UTC, StefanSpieker requested changes

2022-10-17 09:00 UTC, StefanSpieker commented on src/test/java/org/jvnet/hudson/plugins/thinbackup/backup/BackupDirStructureSetup.java
> +    backupDir = tmpFolder.getRoot();
```suggestion
    backupDir = tmpFolder.newFolder("thin-backup");
```

2022-10-17 09:00 UTC, StefanSpieker commented on src/test/java/org/jvnet/hudson/plugins/thinbackup/backup/TestBackupMatrixJob.java
> +    jenkinsHome = TestHelper.createBasicFolderStructure(tmpFolder.getRoot());
see above.

2022-10-17 09:00 UTC, StefanSpieker commented on src/test/java/org/jvnet/hudson/plugins/thinbackup/backup/TestBackupSet.java
> +    final File testFile = new File(tmpFolder.getRoot(), "tempFile.nxt");
```suggestion
    final File testFile = tmpFolder.newFile("tempFile.nxt");
```

2022-10-18 15:57 UTC, StefanSpieker commented on src/test/java/org/jvnet/hudson/plugins/thinbackup/backup/TestBackupMatrixJob.java
> +    backupDir = TestHelper.createBackupFolder(tmpFolder.getRoot());
```suggestion
    backupDir = TestHelper.createBackupFolder(tmpFolder.newFolder("thin-backup"));

```

2022-10-18 15:58 UTC, StefanSpieker commented on src/test/java/org/jvnet/hudson/plugins/thinbackup/backup/TestBackupMatrixJob.java
> +    jenkinsHome = TestHelper.createBasicFolderStructure(tmpFolder.getRoot());
```suggestion
    jenkinsHome = TestHelper.createBasicFolderStructure(tmpFolder.newFolder("jenkins"));
```

2022-10-21 20:30 UTC, mkemmerz commented
I found a solution to why the temp folder of `@Rule` was not created on my Windows system. IntelliJ seems to somehow interfere the System variable for `java.io.tmpdir` to something that wasn't created yet (jUnit expects that the base path is existing). 
**The solution is** to execute the tests with `mvn:test`, instead of using IntelliJ's 'Run tests'. IntelliJ in this case 👎 

Running the tests locally seems fine I think. If you want any additional changes on the code feel free to tell me.

![image](https://user-images.githubusercontent.com/46575727/197283288-b173cb28-d5da-4392-b1b6-1fa2df5e9dff.png)

2022-10-22 10:47 UTC, StefanSpieker approved these changes

2022-11-19 09:35 UTC, StefanSpieker approved these changes

2022-11-19 10:03 UTC, merged

2022-11-19 10:20 UTC, StefanSpieker commented
Thanks a lot @mkemmerz for that. The next release will include your changes.

2022-11-19 10:33 UTC, mkemmerz commented
Let me know if you have some other implementation ideas for other plugins @StefanSpieker 😁